package com.it17327.duan1.DomalModel;
// Generated Nov 19, 2022 2:17:47 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cthd generated by hbm2java
 */
@Entity
@Table(name="CTHD"
    ,schema="dbo"
    ,catalog="ProjectOne"
)
public class Cthd  implements java.io.Serializable {


     private String id;
     private HoaDon hoaDon;
     private Integer soLuong;
     private BigDecimal donGia;
     private BigDecimal donGiaKhiGiam;
     private BigDecimal thanhTien;
     private Set<PhieuBaoHanh> phieuBaoHanhs = new HashSet<PhieuBaoHanh>(0);
     private Set<Serial> serials = new HashSet<Serial>(0);

    public Cthd() {
    }

	
    public Cthd(String id) {
        this.id = id;
    }
    public Cthd(String id, HoaDon hoaDon, Integer soLuong, BigDecimal donGia, BigDecimal donGiaKhiGiam, BigDecimal thanhTien, Set<PhieuBaoHanh> phieuBaoHanhs, Set<Serial> serials) {
       this.id = id;
       this.hoaDon = hoaDon;
       this.soLuong = soLuong;
       this.donGia = donGia;
       this.donGiaKhiGiam = donGiaKhiGiam;
       this.thanhTien = thanhTien;
       this.phieuBaoHanhs = phieuBaoHanhs;
       this.serials = serials;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false, length=10)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdHD")
    public HoaDon getHoaDon() {
        return this.hoaDon;
    }
    
    public void setHoaDon(HoaDon hoaDon) {
        this.hoaDon = hoaDon;
    }

    
    @Column(name="soLuong")
    public Integer getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(Integer soLuong) {
        this.soLuong = soLuong;
    }

    
    @Column(name="donGia", scale=4)
    public BigDecimal getDonGia() {
        return this.donGia;
    }
    
    public void setDonGia(BigDecimal donGia) {
        this.donGia = donGia;
    }

    
    @Column(name="donGiaKhiGiam", scale=4)
    public BigDecimal getDonGiaKhiGiam() {
        return this.donGiaKhiGiam;
    }
    
    public void setDonGiaKhiGiam(BigDecimal donGiaKhiGiam) {
        this.donGiaKhiGiam = donGiaKhiGiam;
    }

    
    @Column(name="ThanhTien", scale=4)
    public BigDecimal getThanhTien() {
        return this.thanhTien;
    }
    
    public void setThanhTien(BigDecimal thanhTien) {
        this.thanhTien = thanhTien;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cthd")
    public Set<PhieuBaoHanh> getPhieuBaoHanhs() {
        return this.phieuBaoHanhs;
    }
    
    public void setPhieuBaoHanhs(Set<PhieuBaoHanh> phieuBaoHanhs) {
        this.phieuBaoHanhs = phieuBaoHanhs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cthd")
    public Set<Serial> getSerials() {
        return this.serials;
    }
    
    public void setSerials(Set<Serial> serials) {
        this.serials = serials;
    }




}


