package com.it17327.duan1.DomalModel;
// Generated Nov 19, 2022 2:17:47 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Serial generated by hbm2java
 */
@Entity
@Table(name="serial"
    ,schema="dbo"
    ,catalog="ProjectOne"
)
public class Serial  implements java.io.Serializable {


     private String imei;
     private ChiTietSp chiTietSp;
     private Cthd cthd;
     private Integer trangThai;

    public Serial() {
    }

	
    public Serial(String imei) {
        this.imei = imei;
    }
    public Serial(String imei, ChiTietSp chiTietSp, Cthd cthd, Integer trangThai) {
       this.imei = imei;
       this.chiTietSp = chiTietSp;
       this.cthd = cthd;
       this.trangThai = trangThai;
    }
   
     @Id 

    
    @Column(name="IMEI", unique=true, nullable=false, length=36)
    public String getImei() {
        return this.imei;
    }
    
    public void setImei(String imei) {
        this.imei = imei;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdCTSP")
    public ChiTietSp getChiTietSp() {
        return this.chiTietSp;
    }
    
    public void setChiTietSp(ChiTietSp chiTietSp) {
        this.chiTietSp = chiTietSp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdCTHD")
    public Cthd getCthd() {
        return this.cthd;
    }
    
    public void setCthd(Cthd cthd) {
        this.cthd = cthd;
    }

    
    @Column(name="TrangThai")
    public Integer getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(Integer trangThai) {
        this.trangThai = trangThai;
    }




}


