package com.it17327.duan1.DomalModel;
// Generated Nov 19, 2022 2:17:47 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="User"
    ,schema="dbo"
    ,catalog="ProjectOne"
)
public class User  implements java.io.Serializable {


     private String id;
     private ChucVu chucVu;
     private Serializable ten;
     private Serializable gioiTinh;
     private Date ngaySinh;
     private Serializable diaChi;
     private String sdt;
     private String matKhau;
     private Integer trangThai;
     private Set<AnhNv> anhNvs = new HashSet<AnhNv>(0);
     private Set<HoaDon> hoaDons = new HashSet<HoaDon>(0);

    public User() {
    }

	
    public User(String id) {
        this.id = id;
    }
    public User(String id, ChucVu chucVu, Serializable ten, Serializable gioiTinh, Date ngaySinh, Serializable diaChi, String sdt, String matKhau, Integer trangThai, Set<AnhNv> anhNvs, Set<HoaDon> hoaDons) {
       this.id = id;
       this.chucVu = chucVu;
       this.ten = ten;
       this.gioiTinh = gioiTinh;
       this.ngaySinh = ngaySinh;
       this.diaChi = diaChi;
       this.sdt = sdt;
       this.matKhau = matKhau;
       this.trangThai = trangThai;
       this.anhNvs = anhNvs;
       this.hoaDons = hoaDons;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, length=10)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdCV")
    public ChucVu getChucVu() {
        return this.chucVu;
    }
    
    public void setChucVu(ChucVu chucVu) {
        this.chucVu = chucVu;
    }

    
    @Column(name="Ten")
    public Serializable getTen() {
        return this.ten;
    }
    
    public void setTen(Serializable ten) {
        this.ten = ten;
    }

    
    @Column(name="GioiTinh")
    public Serializable getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(Serializable gioiTinh) {
        this.gioiTinh = gioiTinh;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NgaySinh", length=10)
    public Date getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }

    
    @Column(name="DiaChi")
    public Serializable getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(Serializable diaChi) {
        this.diaChi = diaChi;
    }

    
    @Column(name="Sdt", length=30)
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

    
    @Column(name="MatKhau")
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }

    
    @Column(name="TrangThai")
    public Integer getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(Integer trangThai) {
        this.trangThai = trangThai;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<AnhNv> getAnhNvs() {
        return this.anhNvs;
    }
    
    public void setAnhNvs(Set<AnhNv> anhNvs) {
        this.anhNvs = anhNvs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<HoaDon> getHoaDons() {
        return this.hoaDons;
    }
    
    public void setHoaDons(Set<HoaDon> hoaDons) {
        this.hoaDons = hoaDons;
    }




}


